// <auto-generated />
using System;
using Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application.Models.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<int>("BestsellerRank")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1750)
                        .HasColumnType("nvarchar(1750)");

                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GenreTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("PublicationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "44b2fbfb-09cd-474e-8",
                            Author = "Diana Gabaldon",
                            BestsellerRank = 132,
                            Country = "United States",
                            Description = "Claire Beauchamp Randall and Jamie Fraser, in a spellbinding novel of passion and history that combines exhilarating adventure with a love story for the ages. Scottish Highlands, 1945. Claire Randall, a former British combat nurse, is just back from the war and reunited with her husband on a second honeymoon when she walks through a standing stone in one of the ancient circles that dot the British Isles. Suddenly she is a Sassenach--an 'outlander'--in a Scotland torn by war and raiding clans in the year of Our Lord . . . 1743. Claire is catapulted into the intrigues of a world that threatens her life, and may shatter her heart. Marooned amid danger, passion, and violence, Claire learns her only chance of safety lies in Jamie Fraser, a gallant young Scots warrior. What begins in compulsion becomes urgent need, and Claire finds herself torn between two very different men, in two irreconcilable lives.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Outlander.jpg",
                            Language = "English",
                            Pages = 896,
                            Price = 16.18,
                            PublicationDate = "01 Aug 1996",
                            Publisher = "Bantam Doubleday Dell Publishing Group Inc",
                            Quantity = 30,
                            Title = "Outlander"
                        },
                        new
                        {
                            Id = "88c95c2a-9e6d-4073-b",
                            Author = "Lucinda Riley",
                            BestsellerRank = 391,
                            Country = "United Kingdom",
                            Description = "After the death of her father - Pa Salt, an elusive billionaire who adopted his six daughters from around the globe - Tiggy D'Apliese , trusting her instincts, moves to the remote wilds of Scotland. There she takes a job doing what she loves; caring for animals on the vast and isolated Kinnaird estate, employed by the enigmatic and troubled Laird, Charlie Kinnaird.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/TheMoonSister.jpg",
                            Language = "English",
                            Pages = 768,
                            Price = 13.75,
                            PublicationDate = "11 Jul 2019",
                            Publisher = "Pan MacMillan",
                            Quantity = 5,
                            Title = "The Moon Sister"
                        },
                        new
                        {
                            Id = "f2c0a884-4202-481b-9",
                            Author = "Casey Mcquiston",
                            BestsellerRank = 11,
                            Country = "United States",
                            Description = "What happens when America's First Son falls in love with the Prince of Wales? When his mother became President, Alex Claremont-Diaz was promptly cast as the American equivalent of a young royal. Handsome, charismatic, genius--his image is pure millennial-marketing gold for the White House.There's only one problem: Alex has a beef with the actual prince, Henry, across the pond. And when the tabloids get hold of a photo involving an Alex-Henry altercation, U.S./British relations take a turn for the worse.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/RedWhiteBlue.jpg",
                            Language = "English",
                            Pages = 432,
                            Price = 31.0,
                            PublicationDate = "14 May 2019",
                            Publisher = "St Martin's Press",
                            Quantity = 3,
                            Title = "Red, White & Royal Blue : A Novel"
                        },
                        new
                        {
                            Id = "4f1a22df-c88b-497b-9",
                            Author = "Colleen Hoover",
                            BestsellerRank = 121,
                            Country = "United Kingdom",
                            Description = "Lily hasn't always had it easy, but that's never stopped her from working hard for the life she wants. She's come a long way from the small town in Maine where she grew up - she graduated from college, moved to Boston, and started her own business. So when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily's life suddenly seems almost too good to be true.Ryle is assertive, stubborn, maybe even a little arrogant. He`s also sensitive, brilliant, and has a total soft spot for Lily, but Ryle`s complete aversion to relationships is disturbing. Even as Lily finds herself becoming the exception to his 'no dating' rule, she can't help but wonder what made him that way in the first place.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Endswithus.jpg",
                            Language = "English",
                            Pages = 384,
                            Price = 19.949999999999999,
                            PublicationDate = "02 Aug 2016",
                            Publisher = "Simon & Schuster Ltd",
                            Quantity = 4,
                            Title = "It Ends With Us"
                        },
                        new
                        {
                            Id = "1c32c562-491c-46ad-8",
                            Author = "Lucinda Riley",
                            BestsellerRank = 264,
                            Country = " United Kingdom",
                            Description = "Following on from the bestselling The Seven Sisters and The Storm Sister, The Shadow Sister is the third book in Lucinda Riley's spellbinding series of love and loss, loosely based on the mythology of the Seven Sisters star cluster.Star D`Apliese is at a crossroads in her life after the sudden death of her beloved father - the elusive billionaire, named Pa Salt by his six daughters, all adopted by him from the four corners of the world. He has left each of them a clue to their true heritage, but Star - the most enigmatic of the sisters - is hesitant to step out of the safety of the close relationship she shares with her sister CeCe. In desperation, she decides to follow the first clue she has been left, which leads her to an antiquarian bookshop in London, and the start of a whole new world . . .",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Theshadowsister.jpg",
                            Language = "English",
                            Pages = 720,
                            Price = 21.82,
                            PublicationDate = "11 Jul 2019",
                            Publisher = "Pan MacMillan",
                            Quantity = 6,
                            Title = "The Shadow Sister"
                        },
                        new
                        {
                            Id = "1c1280d6-bbc3-4bae-b",
                            Author = "Casey Mcquiston",
                            BestsellerRank = 168,
                            Country = "United States",
                            Description = "For cynical twenty-three-year-old August, moving to New York City is supposed to prove her right: that things like magic and cinematic love stories don't exist, and the only smart way to go through life is alone. She can't imagine how waiting tables at a 24-hour pancake diner and moving in with too many weird roommates could possibly change that. And there's certainly no chance of her subway commute being anything more than a daily trudge through boredom and electrical failures.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Onelaststop.jpg",
                            Language = "English",
                            Pages = 432,
                            Price = 24.030000000000001,
                            PublicationDate = "01 Jun 2021",
                            Publisher = "St Martin's Press",
                            Quantity = 0,
                            Title = "One Last Stop"
                        },
                        new
                        {
                            Id = "c0c8af65-58ad-47fc-a",
                            Author = "Morgan Rogers",
                            BestsellerRank = 280,
                            Country = "United States",
                            Description = "With her newly completed PhD in astronomy in hand, twenty-eight-year-old Grace Porter goes on a girls' trip to Vegas to celebrate. She's a straight A, work-through-the-summer certified high achiever. She is not the kind of person who goes to Vegas and gets drunkenly married to a woman whose name she doesn't know...until she does exactly that. This one moment of departure from her stern ex-military father's plans for her life has Grace wondering why she doesn`t feel more fulfilled from completing her degree. Staggering under the weight of her parent's expectations, a struggling job market and feelings of burnout, Grace flees her home in Portland for a summer in New York with the wife she barely knows.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Honeygirl.jpg",
                            Language = "English",
                            Pages = 304,
                            Price = 17.84,
                            PublicationDate = "23 Feb 2021",
                            Publisher = "Park Row",
                            Quantity = 0,
                            Title = "Honey Girl"
                        },
                        new
                        {
                            Id = "f897f398-006d-43e4-8",
                            Author = "Sally Rooney",
                            BestsellerRank = 141,
                            Country = "United Kingdom",
                            Description = "Connell and Marianne grow up in the same small town in the west of Ireland, but the similarities end there. In school, Connell is popular and well-liked, while Marianne is a loner. But when the two strike up a conversation - awkward but electrifying - something life-changing begins. Normal People is a story of mutual fascination, friendship and love. It takes us from that first conversation to the years beyond, in the company of two people who try to stay apart but find they can't.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Normalpoeple.jpg",
                            Language = "English",
                            Pages = 288,
                            Price = 19.57,
                            PublicationDate = "23 Jul 2019",
                            Publisher = "FABER & FABER",
                            Quantity = 2,
                            Title = "Normal People"
                        },
                        new
                        {
                            Id = "c74d27db-3009-4552-b",
                            Author = " Rainbow Rowell",
                            BestsellerRank = 149,
                            Country = "United Kingdom",
                            Description = "Cath and Wren are identical twins, and until recently they did absolutely everything together. Now they're off to university and Wren's decided she doesn't want to be one half of a pair any more - she wants to dance, meet boys, go to parties and let loose. It's not so easy for Cath. She's horribly shy and has always buried herself in the fan fiction she writes, where she always knows exactly what to say and can write a romance far more intense than anything she's experienced in real life.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Fangirl.jpg",
                            Language = "English",
                            Pages = 480,
                            Price = 19.57,
                            PublicationDate = "30 Jan 2014",
                            Publisher = "Pan MacMillan",
                            Quantity = 20,
                            Title = "Fangirl"
                        },
                        new
                        {
                            Id = "077dacd7-2fd5-49cb-9",
                            Author = " Rainbow Rowell",
                            BestsellerRank = 264,
                            Country = "United Kingdom",
                            Description = "Eleanor is the new girl in town, and she's never felt more alone. All mismatched clothes, mad red hair and chaotic home life, she couldn't stick out more if she tried. Then she takes the seat on the bus next to Park. Quiet, careful and - in Eleanor's eyes - impossibly cool, Park's worked out that flying under the radar is the best way to get by. Slowly, steadily, through late-night conversations and an ever-growing stack of mix tapes, Eleanor and Park fall in love. They fall in love the way you do the first time, when you're 16, and you have nothing and everything to lose.",
                            GenreTitle = "Romance",
                            ImageUrl = "https://localhost:5001/images/romance/Eleanorpark.jpg",
                            Language = "English",
                            Pages = 336,
                            Price = 17.050000000000001,
                            PublicationDate = "07 Jul 2014",
                            Publisher = "Orion Publishing Co",
                            Quantity = 12,
                            Title = "Eleanor & Park"
                        },
                        new
                        {
                            Id = "4f172e5a-83fc-49f7-9",
                            Author = "Stephen King",
                            BestsellerRank = 156,
                            Country = "United States",
                            Description = "Before Doctor Sleep, there was The Shining, a classic of modern American horror from the undisputed master, Stephen King. Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote . . . and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old.",
                            GenreTitle = "Horror",
                            ImageUrl = "https://localhost:5001/images/horror/TheShining.jpg",
                            Language = "English",
                            Pages = 688,
                            Price = 10.539999999999999,
                            PublicationDate = "07 Feb 2020",
                            Publisher = "Random House USA Inc",
                            Quantity = 25,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = "3f686227-8995-47b4-b",
                            Author = "Stephen King",
                            BestsellerRank = 160,
                            Country = "United Kingdom",
                            Description = "Derry, Maine is just an ordinary town: familiar, well-ordered for the most part, a good place to live. It is a group of children who see - and feel - what makes Derry so horribly different. In the storm drains, in the sewers, IT lurks, taking on the shape of every nightmare, each one's deepest dread. Sometimes is appears as an evil clown named Pennywise and sometimes IT reaches up, seizing, tearing, killing . . . Time passes and the children grow up, move away and forget. Until they are called back, once more to confront IT as IT stirs and coils in the sullen depths of their memories, emerging again to make their past nightmares a terrible present reality.",
                            GenreTitle = "Horror",
                            ImageUrl = "https://localhost:5001/images/horror/It.jpg",
                            Language = "English",
                            Pages = 1184,
                            Price = 17.989999999999998,
                            PublicationDate = "21 Jul 2011",
                            Publisher = "HODDER & STOUGHTON",
                            Quantity = 21,
                            Title = "It"
                        },
                        new
                        {
                            Id = "784ca575-b663-4121-a",
                            Author = "Shirley Jackson",
                            BestsellerRank = 579,
                            Country = "United Kingdom",
                            Description = "Alone in the world, Eleanor is delighted to take up Dr Montague's invitation to spend a summer in the mysterious Hill House. Joining them are Theodora, an artistic 'sensitive', and Luke, heir to the house. But what begins as a light-hearted experiment is swiftly proven to be a trip into their darkest nightmares, and an investigation that one of their number may not survive. Twice filmed as The Haunting, and the inspiration for a 10-part Netflix series, The Haunting of Hill House is a powerful work of slow-burning psychological horror.",
                            GenreTitle = "Horror",
                            ImageUrl = "https://localhost:5001/images/horror/TheHaunting.jpg",
                            Language = "English",
                            Pages = 256,
                            Price = 20.309999999999999,
                            PublicationDate = "01 Oct 2009",
                            Publisher = "Penguin Books Ltd",
                            Quantity = 4,
                            Title = "The Haunting of Hill House"
                        },
                        new
                        {
                            Id = "af645778-4861-4549-9",
                            Author = "Bret Easton Ellis",
                            BestsellerRank = 303,
                            Country = "United States",
                            Description = "In American Psycho, Bret Easton Ellis imaginatively explores the incomprehensible depths of madness and captures the insanity of violence in our time or any other. Patrick Bateman moves among the young and trendy in 1980s Manhattan. Young, handsome, and well educated, Bateman earns his fortune on Wall Street by day while spending his nights in ways we cannot begin to fathom. Expressing his true self through torture and murder, Bateman prefigures an apocalyptic horror that no society could bear to confront.",
                            GenreTitle = "Horror",
                            ImageUrl = "https://localhost:5001/images/horror/AmericanPsycho.jpg",
                            Language = "English",
                            Pages = 416,
                            Price = 15.130000000000001,
                            PublicationDate = "06 Jun 2008",
                            Publisher = "Random House USA Inc",
                            Quantity = 0,
                            Title = "American Psycho"
                        },
                        new
                        {
                            Id = "bbf39443-729b-40d6-b",
                            Author = " Mary Shelley",
                            BestsellerRank = 491,
                            Country = "United Kingdom",
                            Description = "A twisted, upside-down creation myth, Mary Shelley's chilling Gothic tale lays bare the dark side of science, and the horror within us all. It tells the story of Victor Frankenstein, who plunders graveyards to create a new being from the bodies of the dead - but whose botched creature causes nothing but murder and destruction. Written after a nightmare when its author was only eighteen, Frankenstein gave birth to the modern science fiction novel.",
                            GenreTitle = "Horror",
                            ImageUrl = "https://localhost:5001/images/horror/Frankenstein.jpg",
                            Language = "English",
                            Pages = 288,
                            Price = 17.809999999999999,
                            PublicationDate = "01 May 2012",
                            Publisher = "Penguin Books Ltd",
                            Quantity = 20,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = "213fe91d-2f55-485c-b",
                            Author = "Bram Stoker",
                            BestsellerRank = 342,
                            Country = " United Kingdom",
                            Description = "There he lay looking as if youth had been half-renewed, for the white hair and moustache were changed to dark iron-grey, the cheeks were fuller, and the white skin seemed ruby-red underneath; the mouth was redder than ever, for on the lips were gouts of fresh blood, which trickled from the corners of the mouth and ran over the chin and neck. Even the deep, burning eyes seemed set amongst the swollen flesh, for the lids and pouches underneath were bloated. It seemed as if the whole awful creature were simply gorged with blood; he lay like a filthy leech, exhausted with his repletion.",
                            GenreTitle = "Horror",
                            ImageUrl = "https://localhost:5001/images/horror/Dracula.jpg",
                            Language = "English",
                            Pages = 532,
                            Price = 10.23,
                            PublicationDate = "01 Aug 1997",
                            Publisher = "Wordsworth Editions Ltd",
                            Quantity = 3,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = "b97b6019-b802-4f83-a",
                            Author = "John Fowles",
                            BestsellerRank = 604,
                            Country = "United Kingdom",
                            Description = "Withdrawn, uneducated and unloved, Frederick collects butterflies and takes photographs. He is obsessed with a beautiful stranger, art student Miranda. Coming into unexpected money, he buys a remote Sussex house and calmly abducts Miranda, believing she will grow to love him in time. Alone and desperate, Miranda must struggle to understand her captor if she is to gain her freedom...",
                            GenreTitle = "Horror",
                            ImageUrl = "https://localhost:5001/images/horror/Thecollector.jpg",
                            Language = "English",
                            Pages = 288,
                            Price = 14.26,
                            PublicationDate = "30 Nov 2007",
                            Publisher = "Vintage Publishing",
                            Quantity = 0,
                            Title = "The Collector"
                        },
                        new
                        {
                            Id = "7d2cbd34-a5ad-4ff6-b",
                            Author = "Ed Bryan",
                            BestsellerRank = 918,
                            Country = "United Kingdom",
                            Description = "When the wicked queen discovers that her stepdaughter, Snow White, is the most beautiful woman in the land, she orders the huntsman to kill her. But Snow White escapes and finds a wonderful new home living with seven friendly dwarfs in a cosy cottage. That is, until the wicked queen pays a visit . . . It's up to the seven dwarfs and a very kind prince to defeat the queen and help Snow White live happily ever after!",
                            GenreTitle = "Children's Books",
                            ImageUrl = "https://localhost:5001/images/childrenbooks/SnowWhite.jpg",
                            Language = "English",
                            Pages = 32,
                            Price = 18.600000000000001,
                            PublicationDate = "04 Jul 2019",
                            Publisher = "Nosy Crow Ltd",
                            Quantity = 13,
                            Title = "Fairy Tales: Snow White"
                        },
                        new
                        {
                            Id = "c42c79f4-2b58-4d02-9",
                            Author = "Ed Bryan",
                            BestsellerRank = 651,
                            Country = "United Kingdom",
                            Description = "When Goldilocks gets lost in the woods, she finds herself at a cosy little cottage. She is delighted to find three bowls of porridge on the table, three chairs in the living room and some very bouncy beds in the bedroom. But little does Goldilocks know, this cottage belongs to three bears, and they're on their way back home . . .",
                            GenreTitle = "Children's Books",
                            ImageUrl = "https://localhost:5001/images/childrenbooks/Goldilocks.jpg",
                            Language = "English",
                            Pages = 32,
                            Price = 18.600000000000001,
                            PublicationDate = "07 Mar 2019",
                            Publisher = "Nosy Crow Ltd",
                            Quantity = 12,
                            Title = "Fairy Tales: Goldilocks and the Three Bears"
                        },
                        new
                        {
                            Id = "dac131e0-8b02-41b2-9",
                            Author = "Nosy Crow",
                            BestsellerRank = 781,
                            Country = "United Kingdom",
                            Description = "Little Red Riding Hood sets out into the forest to take a basket of goodies to her poorly grandma. Along the way, she adds to her stores, picking beautiful flowers, gathering fallen acorns and receiving a gift of some nice, sticky honey. She thinks these treats will cheer up her grandma. But little does she know that they could just save her from the Big Bad Wolf . . .",
                            GenreTitle = "Children's Books",
                            ImageUrl = "https://localhost:5001/images/childrenbooks/LittleRedRidingHood.jpg",
                            Language = "English",
                            Pages = 32,
                            Price = 18.600000000000001,
                            PublicationDate = "31 Dec 2016",
                            Publisher = "Nosy Crow Ltd",
                            Quantity = 2,
                            Title = "Fairy Tales: Little Red Riding Hood"
                        },
                        new
                        {
                            Id = "0732f3b0-ffcd-4c1d-a",
                            Author = "Yung Pueblo",
                            BestsellerRank = 152,
                            Country = "United States",
                            Description = "In Clarity & Connection, Yung Pueblo describes how intense emotions accumulate in our subconscious and condition us to act and react in certain ways. In his characteristically spare, poetic style, he guides readers through the excavation and release of the past that is required for growth.",
                            GenreTitle = "Poetry & Drama",
                            ImageUrl = "https://localhost:5001/images/poetry&drama/Clarity.jpg",
                            Language = "English",
                            Pages = 256,
                            Price = 29.789999999999999,
                            PublicationDate = "27 May 2021",
                            Publisher = "Andrews McMeel Publishing",
                            Quantity = 5,
                            Title = "Clarity & Connection"
                        },
                        new
                        {
                            Id = "1cb0881e-babc-421b-b",
                            Author = "Rupi Kaur",
                            BestsellerRank = 332,
                            Country = "United States",
                            Description = "The book is divided into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. Milk and Honey takes readers through a journey of the most bitter moments in life and finds sweetness in them because there is sweetness everywhere if you are just willing to look.",
                            GenreTitle = "Poetry & Drama",
                            ImageUrl = "https://localhost:5001/images/poetry&drama/",
                            Language = "English",
                            Pages = 208,
                            Price = 2014.0,
                            PublicationDate = "08 Jul 2016",
                            Publisher = "Andrews McMeel Publishing",
                            Quantity = 208,
                            Title = "Milk and Honey"
                        },
                        new
                        {
                            Id = "b5dcdc02-369e-4b66-a",
                            Author = "Yung Pueblo",
                            BestsellerRank = 138,
                            Country = "United States",
                            Description = "From poet, meditator, and speaker Yung Pueblo, comes a collection of poetry and prose that explores the movement from self-love to unconditional love, the power of letting go, and the wisdom that comes when we truly try to know ourselves. It serves as a reminder to the reader that healing, transformation, and freedom are possible.",
                            GenreTitle = "Poetry & Drama",
                            ImageUrl = "https://localhost:5001/images/poetry&drama/Inward.jpg",
                            Language = "English",
                            Pages = 240,
                            Price = 23.989999999999998,
                            PublicationDate = "05 Aug 2020",
                            Publisher = "Andrews McMeel Publishing",
                            Quantity = 20,
                            Title = "Inward"
                        },
                        new
                        {
                            Id = "84102564-c20d-4705-8",
                            Author = " George Orwell",
                            BestsellerRank = 49,
                            Country = "United Kingdom",
                            Description = "Winston Smith works for the Ministry of Truth in London, chief city of Airstrip One. Big Brother stares out from every poster, the Thought Police uncover every act of betrayal. When Winston finds love with Julia, he discovers that life does not have to be dull and deadening, and awakens to new possibilities. Despite the police helicopters that hover and circle overhead, Winston and Julia begin to question the Party; they are drawn towards conspiracy. Yet Big Brother will not tolerate dissent - even in the mind. For those with original thoughts they invented Room 101. . .",
                            GenreTitle = "Thriller",
                            ImageUrl = "https://localhost:5001/images/thriller/1984.jpg",
                            Language = "English",
                            Pages = 336,
                            Price = 15.289999999999999,
                            PublicationDate = "01 Oct 2008",
                            Publisher = " Penguin Books Ltd",
                            Quantity = 0,
                            Title = "1984 : The dystopian classic"
                        },
                        new
                        {
                            Id = "98f27d9a-3016-4f3b-a",
                            Author = "George Orwell",
                            BestsellerRank = 77,
                            Country = "United Kingdom",
                            Description = "Mr Jones of Manor Farm is so lazy and drunken that one day he forgets to feed his livestock. The ensuing rebellion under the leadership of the pigs Napoleon and Snowball leads to the animals taking over the farm. Vowing to eliminate the terrible inequities of the farmyard, the renamed Animal Farm is organised to benefit all who walk on four legs. But as time passes, the ideals of the rebellion are corrupted, then forgotten. And something new and unexpected emerges. . .",
                            GenreTitle = "Thriller",
                            ImageUrl = "https://localhost:5001/images/thriller/AnimalFarm.jpg",
                            Language = "English",
                            Pages = 112,
                            Price = 23.149999999999999,
                            PublicationDate = "01 Oct 2008",
                            Publisher = "Penguin Books Ltd",
                            Quantity = 20,
                            Title = "Animal Farm : The dystopian classic"
                        },
                        new
                        {
                            Id = "94c09792-5b15-46e1-8",
                            Author = "Andy Weir",
                            BestsellerRank = 980,
                            Country = "United Kingdom",
                            Description = "Jazz Bashara is one of the criminals. She lives in a poor area of Artemis and subsidises her work as a porter with smuggling contraband onto the moon. But it's not enough.So when she's offered the chance to make a lot of money she jumps at it. But though planning a crime in 1/6th gravity may be more fun, it's also a lot more dangerous.When you live on the moon, of course you have a dark side...",
                            GenreTitle = "Science Fiction",
                            ImageUrl = "https://localhost:5001/images/fiction/Artemis.jpg",
                            Language = "English",
                            Pages = 320,
                            Price = 21.66,
                            PublicationDate = "12 Jul 2018",
                            Publisher = "Cornerstone",
                            Quantity = 2,
                            Title = "Artemis"
                        },
                        new
                        {
                            Id = "6ca810a3-5b3a-4dae-b",
                            Author = "Orson Scott Card",
                            BestsellerRank = 461,
                            Country = "United States",
                            Description = "Ender's Game is the classic Hugo and Nebula award-winning science fiction novel of a young boy's recruitment into the midst of an interstellar war. In order to develop a secure defense against a hostile alien race's next attack, government agencies breed child geniuses and train them as soldiers. A brilliant young boy, Andrew Ender Wiggin lives with his kind but distant parents, his sadistic brother Peter, and the person he loves more than anyone else, his sister Valentine. Peter and Valentine were candidates for the soldier-training program but didn't make the cut--young Ender is the Wiggin drafted to the orbiting Battle School for rigorous military training. Ender's skills make him a leader in school and respected in the Battle Room, where children play at mock battles in zero gravity. Yet growing up in an artificial community of young soldiers Ender suffers greatly from isolation, rivalry from his peers, pressure from the adult teachers, and an unsettling fear of the alien invaders. His psychological battles include loneliness, fear that he is becoming like the cruel brother he remembers, and fanning the flames of devotion to his beloved sister. ",
                            GenreTitle = "Science Fiction",
                            ImageUrl = "https://localhost:5001/images/fiction/EndersGame.jpg",
                            Language = "English",
                            Pages = 375,
                            Price = 18.850000000000001,
                            PublicationDate = "30 Nov 1998",
                            Publisher = "Tor Books",
                            Quantity = 3,
                            Title = "Ender's Game"
                        },
                        new
                        {
                            Id = "a6840c62-d29c-4578-9",
                            Author = "Cixin Liu ",
                            BestsellerRank = 166,
                            Country = " United Kingdom",
                            Description = "Earth enjoys unprecedented prosperity due to the infusion of Trisolaran knowledge and, with human science advancing and the Trisolarans adopting Earth culture, it seems that the two civilizations can co-exist peacefully as equals without the terrible threat of mutually assured annihilation. But peace has made humanity complacent.",
                            GenreTitle = "Science Fiction",
                            ImageUrl = "https://localhost:5001/images/fiction/DeathsEnd.jpg",
                            Language = "English",
                            Pages = 608,
                            Price = 27.5,
                            PublicationDate = "04 May 2017",
                            Publisher = "Head of Zeus",
                            Quantity = 20,
                            Title = "Death's End"
                        });
                });

            modelBuilder.Entity("Application.Models.Genre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = "4d88758d-f63e-42df-8",
                            Description = "All Fiction Books",
                            Title = "Science Fiction"
                        },
                        new
                        {
                            Id = "c8cee82f-58a6-4fd3-8",
                            Description = "All Romance Books",
                            Title = "Romance"
                        },
                        new
                        {
                            Id = "be6db1ea-cf0e-41f2-8",
                            Description = "All Horror  Books",
                            Title = "Horror"
                        },
                        new
                        {
                            Id = "20eabe0a-ce27-4045-9",
                            Description = "All Poetry & Drama Books",
                            Title = "Poetry & Drama"
                        },
                        new
                        {
                            Id = "b02ca48f-f6cb-40ae-a",
                            Description = "All Thriller Books",
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = "cbdd84fc-af58-42ab-9",
                            Description = "All Children's Books Books",
                            Title = "Children's Books"
                        });
                });

            modelBuilder.Entity("Application.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Application.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Application.Models.Book", b =>
                {
                    b.HasOne("Application.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Application.Models.Order", b =>
                {
                    b.HasOne("Application.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Application.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Application.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
